# version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: YourPassword
      POSTGRES_DB: librarydb
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend/LibraryApi
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"
volumes:
  pgdata:
